/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ScheduleEntry = {
  _id: string;
  _type: "scheduleEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  dayIndex?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  startTime?: string;
  endTime?: string;
  classType?: "Gi" | "No-Gi" | "Kids" | "Open Mat";
  level?: "all" | "beg" | "adv" | "kids";
  coach?: string;
  location?: "KE" | "BA";
};

export type RecurringEvent = {
  _id: string;
  _type: "recurringEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  dayOfWeek?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
  time?: string;
  place?: LocalizedString;
};

export type LocalizedString = {
  _type: "localizedString";
  sk?: string;
  en?: string;
  ua?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventType?: "seminar" | "tournament" | "workshop" | "camp";
  startDate?: string;
  endDate?: string;
  title?: LocalizedString;
  description?: LocalizedText;
  place?: LocalizedString;
};

export type LocalizedText = {
  _type: "localizedText";
  sk?: string;
  en?: string;
  ua?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  hero?: HeroSection;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type HeroSection = {
  _type: "heroSection";
  kicker?: LocalizedString;
  title?: LocalizedString;
  subtitle?: LocalizedText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocalizedString;
    _type: "image";
  };
  stats?: Array<
    {
      _key: string;
    } & HeroStat
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type HeroStat = {
  _type: "heroStat";
  value?: string;
  label?: LocalizedString;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ScheduleEntry
  | RecurringEvent
  | LocalizedString
  | Event
  | LocalizedText
  | SiteSettings
  | SanityImageAssetReference
  | HeroSection
  | Page
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | HeroStat
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/utils/sanity.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page" && defined(slug.current)] | order(_createdAt desc){    _id,    title,    "slug": slug.current,    excerpt  }
export type PAGES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
}>;

// Source: ../web/src/utils/sanity.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    body  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Source: ../web/src/utils/sanity.ts
// Variable: PAGE_PATHS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    _id,    title,    "slug": slug.current,    excerpt,    body  }
export type PAGE_PATHS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;

// Source: ../web/src/utils/sanity.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{    "params": { "slug": slug.current }  }
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  params: {
    slug: string | null;
  };
}>;

// Source: ../web/src/utils/sanity.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    title,    description  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
} | null;

// Source: ../web/src/utils/sanity/events.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event"] | order(startDate asc){    eventType,    startDate,    endDate,    title,    description,    place  }
export type EVENTS_QUERY_RESULT = Array<{
  eventType: "camp" | "seminar" | "tournament" | "workshop" | null;
  startDate: string | null;
  endDate: string | null;
  title: LocalizedString | null;
  description: LocalizedText | null;
  place: LocalizedString | null;
}>;

// Source: ../web/src/utils/sanity/events.ts
// Variable: RECURRING_EVENTS_QUERY
// Query: *[_type == "recurringEvent"] | order(dayOfWeek asc, time asc){    title,    dayOfWeek,    time,    place  }
export type RECURRING_EVENTS_QUERY_RESULT = Array<{
  title: LocalizedString | null;
  dayOfWeek: 0 | 1 | 2 | 3 | 4 | 5 | 6 | null;
  time: string | null;
  place: LocalizedString | null;
}>;

// Source: ../web/src/utils/sanity/hero.ts
// Variable: HERO_QUERY
// Query: *[_type == "siteSettings"][0]{    hero {      kicker,      title,      subtitle,      image {        asset,        hotspot,        crop,        alt      },      stats[] {        value,        label      }    }  }
export type HERO_QUERY_RESULT = {
  hero: {
    kicker: LocalizedString | null;
    title: LocalizedString | null;
    subtitle: LocalizedText | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: LocalizedString | null;
    } | null;
    stats: Array<{
      value: string | null;
      label: LocalizedString | null;
    }> | null;
  } | null;
} | null;

// Source: ../web/src/utils/sanity/schedule.ts
// Variable: SCHEDULE_QUERY
// Query: *[_type == "scheduleEntry"] | order(dayIndex asc, startTime asc){    dayIndex,    startTime,    endTime,    classType,    level,    coach,    location  }
export type SCHEDULE_QUERY_RESULT = Array<{
  dayIndex: 0 | 1 | 2 | 3 | 4 | 5 | 6 | null;
  startTime: string | null;
  endTime: string | null;
  classType: "Gi" | "Kids" | "No-Gi" | "Open Mat" | null;
  level: "adv" | "all" | "beg" | "kids" | null;
  coach: string | null;
  location: "BA" | "KE" | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "page" && defined(slug.current)] | order(_createdAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt\n  }': PAGES_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    body\n  }': PAGE_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    body\n  }': PAGE_PATHS_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)]{\n    "params": { "slug": slug.current }\n  }': PAGE_SLUGS_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n    title,\n    description\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "event"] | order(startDate asc){\n    eventType,\n    startDate,\n    endDate,\n    title,\n    description,\n    place\n  }': EVENTS_QUERY_RESULT;
    '*[_type == "recurringEvent"] | order(dayOfWeek asc, time asc){\n    title,\n    dayOfWeek,\n    time,\n    place\n  }': RECURRING_EVENTS_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n    hero {\n      kicker,\n      title,\n      subtitle,\n      image {\n        asset,\n        hotspot,\n        crop,\n        alt\n      },\n      stats[] {\n        value,\n        label\n      }\n    }\n  }': HERO_QUERY_RESULT;
    '*[_type == "scheduleEntry"] | order(dayIndex asc, startTime asc){\n    dayIndex,\n    startTime,\n    endTime,\n    classType,\n    level,\n    coach,\n    location\n  }': SCHEDULE_QUERY_RESULT;
  }
}
